#!/usr/bin/python3
# -*- coding: utf-8 -*-

""" Copyright 2017 Kallyous Caos Negro
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License. """

import os, sys, snek
from snek.snekclient import GameClient

snek.GAME_HOME = os.path.dirname( os.path.realpath(__file__) )
snek.SCRIPTS_PATH = u'%s/scripts' % snek.GAME_HOME

sys.path.append(snek.GAME_HOME)
sys.path.append(snek.SCRIPTS_PATH)

game = GameClient()

game.start()




















