CREATE TABLE player (
id INTEGER PRIMARY KEY AUTOINCREMENT,
username TEXT NOT NULL,
level INT UNSIGNED DEFAULT 0,
exp INT UNSIGNED DEFAULT 0,
class INT UNSIGNED DEFAULT 0,
loc_curr_world INT UNSIGNED DEFAULT 2,
loc_curr_world_lvl INT UNSIGNED DEFAULT 0,
loc_curr_x INT UNSIGNED DEFAULT 16,
loc_curr_y INT UNSIGNED DEFAULT 16,
loc_curr_z INT UNSIGNED DEFAULT 0,
loc_spawn_world INT UNSIGNED DEFAULT 2,
loc_spawn_world_lvl INT UNSIGNED DEFAULT 0,
loc_spawn_x INT UNSIGNED DEFAULT 16,
loc_spawn_y INT UNSIGNED DEFAULT 16,
loc_spawn_z INT UNSIGNED DEFAULT 0,
password TEXT NOT NULL,
email TEXT NOT NULL
);
